export const roles = [
  {
    id: '063f23af-ea20-4f5e-b209-0cb8e9bf9bea',
    name: 'Visualizar Permissões',
    active: true,
    created_at: new Date(),
    action: 'get',
    module: 'management',
    type: 'Permissões',
  },
  {
    id: '0da07c43-5d5f-485d-bf77-65b927c3bbfb',
    name: 'Visualizar usuário',
    active: true,
    created_at: new Date(),
    action: 'get',
    module: 'management',
    type: 'Usuários',
  },
  {
    id: '1399b962-835d-4883-9abc-662964e95af2',
    name: 'Visualizar o menu de Financeiro',
    active: true,
    created_at: new Date(),
    action: 'get',
    module: 'finantial',
    type: 'Menu',
  },
  {
    id: '4943cfe2-f8ab-41e2-b9fa-3a50e6215a0f',
    name: 'Visualizar o menu de Cadastro',
    active: true,
    created_at: new Date(),
    action: 'get',
    module: 'registration',
    type: 'Menu',
  },
  {
    id: '4943cfe2-f8ab-41e2-b9fa-3a50e6215a0d',
    name: 'Deletar contas a pagar',
    active: true,
    created_at: new Date(),
    action: 'delete',
    module: 'finantial',
    type: 'Contas a pagar',
  },
  {
    id: '83802737-cad8-4c6a-9a26-c4cb01943513',
    name: 'Permite criar novos fornecedores',
    active: true,
    created_at: new Date(),
    action: 'post_put',
    module: 'registration',
    type: 'Permissões',
  },
  {
    id: '98eb9dfd-6104-40de-9063-8213ae7b17d5',
    name: 'Incluir/Alterar contas a pagar',
    active: true,
    created_at: new Date(),
    action: 'post_put',
    module: 'finantial',
    type: 'Permissões',
  },
  {
    id: 'acd6894d-e6b5-459f-85ba-208ec8c9df0f',
    name: 'Criar/Alterar usuário',
    active: true,
    created_at: new Date(),
    action: 'post_put',
    module: 'management',
    type: 'Permissões',
  },
  {
    id: 'b6a8cf52-8697-469f-ba1f-78a044c15b42',
    name: 'Visualizar contas a pagar',
    active: true,
    created_at: new Date(),
    action: 'get',
    module: 'finantial',
    type: 'Permissões',
  },
  {
    id: 'bb9d0fdd-ec56-43e0-b6d3-6207d845f07c',
    name: 'Deletar Permissões',
    active: true,
    created_at: new Date(),
    action: 'delete',
    module: 'management',
    type: 'Permissões',
  },
  {
    id: 'be55f9f5-f109-4c56-9161-657efa35d3ff',
    name: 'Criar/Alterar Permissões',
    active: true,
    created_at: new Date(),
    action: 'post_put',
    module: 'management',
    type: 'Permissões',
  },
  {
    id: 'da74da4a-bd17-4cfe-aa12-91b87da4245a',
    name: 'Deletar usuário',
    active: true,
    created_at: new Date(),
    action: 'delete',
    module: 'management',
    type: 'Permissões',
  },
  {
    id: 'e21eae61-a70e-4c53-aba5-f8a52717488c',
    name: 'Visualizar o menu de Contratos',
    active: true,
    created_at: new Date(),
    action: 'get',
    module: 'contract',
    type: 'Permissões',
  },
  {
    id: 'e5bf6d26-56ab-406a-b294-cc9bd855e411',
    name: 'Visualizar o menu de Gestão',
    active: true,
    created_at: new Date(),
    action: 'get',
    module: 'management',
    type: 'Permissões',
  },
];
