export const roles = [
  {
    id: '6bcaa508-8e74-4e90-bdfe-54443297a27f',
    name: 'Deletar contas a pagar',
    active: true,
    created_at: new Date(),
    updated_at: new Date(),
    action: 'delete',
    created_by: null,
    deleted_at: null,
    deleted_by: null,
    module: 'financial',
    updated_by: null,
    type: 'Contas a pagar',
  },
  {
    id: '98eb9dfd-6104-40de-9063-8213ae7b17d5',
    name: 'Incluir/Alterar contas a pagar',
    active: true,
    created_at: new Date(),
    updated_at: new Date(),
    action: 'post_put',
    created_by: null,
    deleted_at: null,
    deleted_by: null,
    module: 'financial',
    updated_by: null,
    type: 'Contas a pagar',
  },
  {
    id: 'b6a8cf52-8697-469f-ba1f-78a044c15b42',
    name: 'Visualizar contas a pagar',
    active: true,
    created_at: new Date(),
    updated_at: new Date(),
    action: 'get',
    created_by: null,
    deleted_at: null,
    deleted_by: null,
    module: 'financial',
    updated_by: null,
    type: 'Contas a pagar',
  },
  {
    id: '83802737-cad8-4c6a-9a26-c4cb01943513',
    name: 'Permite criar novos fornecedores',
    active: true,
    created_at: new Date(),
    updated_at: new Date(),
    action: 'post_put',
    created_by: null,
    deleted_at: null,
    deleted_by: null,
    module: 'registration',
    updated_by: null,
    type: 'Fornecedor',
  },
  {
    id: 'e21eae61-a70e-4c53-aba5-f8a52717488c',
    name: 'Visualizar o menu de Contratos',
    active: true,
    created_at: new Date(),
    updated_at: new Date(),
    action: 'get',
    created_by: null,
    deleted_at: null,
    deleted_by: null,
    module: 'contract',
    updated_by: null,
    type: 'Menu',
  },
  {
    id: '1399b962-835d-4883-9abc-662964e95af2',
    name: 'Visualizar o menu de Financeiro',
    active: true,
    created_at: new Date(),
    updated_at: new Date(),
    action: 'get',
    created_by: null,
    deleted_at: null,
    deleted_by: null,
    module: 'financial',
    updated_by: null,
    type: 'Menu',
  },
  {
    id: 'e5bf6d26-56ab-406a-b294-cc9bd855e411',
    name: 'Visualizar o menu de Gestão',
    active: true,
    created_at: new Date(),
    updated_at: new Date(),
    action: 'get',
    created_by: null,
    deleted_at: null,
    deleted_by: null,
    module: 'management',
    updated_by: null,
    type: 'Menu',
  },
  {
    id: '4943cfe2-f8ab-41e2-b9fa-3a50e6215a0f',
    name: 'Visualizar o menu de Cadastro',
    active: true,
    created_at: new Date(),
    updated_at: new Date(),
    action: 'get',
    created_by: null,
    deleted_at: null,
    deleted_by: null,
    module: 'registration',
    updated_by: null,
    type: 'Menu',
  },
  {
    id: '063f23af-ea20-4f5e-b209-0cb8e9bf9bea',
    name: 'Visualizar Permissões',
    active: true,
    created_at: new Date(),
    updated_at: new Date(),
    action: 'get',
    created_by: null,
    deleted_at: null,
    deleted_by: null,
    module: 'management',
    updated_by: null,
    type: 'Permissões',
  },
  {
    id: 'bb9d0fdd-ec56-43e0-b6d3-6207d845f07c',
    name: 'Deletar Permissões',
    active: true,
    created_at: new Date(),
    updated_at: new Date(),
    action: 'delete',
    created_by: null,
    deleted_at: null,
    deleted_by: null,
    module: 'management',
    updated_by: null,
    type: 'Permissões',
  },
  {
    id: 'be55f9f5-f109-4c56-9161-657efa35d3ff',
    name: 'Criar/Alterar Permissões',
    active: true,
    created_at: new Date(),
    updated_at: new Date(),
    action: 'post_put',
    created_by: null,
    deleted_at: null,
    deleted_by: null,
    module: 'management',
    updated_by: null,
    type: 'Permissões',
  },
  {
    id: '0da07c43-5d5f-485d-bf77-65b927c3bbfb',
    name: 'Visualizar usuário',
    active: true,
    created_at: new Date(),
    updated_at: new Date(),
    action: 'get',
    created_by: null,
    deleted_at: null,
    deleted_by: null,
    module: 'management',
    updated_by: null,
    type: 'Usuários',
  },
  {
    id: 'acd6894d-e6b5-459f-85ba-208ec8c9df0f',
    name: 'Criar/Alterar usuário',
    active: true,
    created_at: new Date(),
    updated_at: new Date(),
    action: 'post_put',
    created_by: null,
    deleted_at: null,
    deleted_by: null,
    module: 'management',
    updated_by: null,
    type: 'Usuários',
  },
  {
    id: 'da74da4a-bd17-4cfe-aa12-91b87da4245a',
    name: 'Deletar usuário',
    active: true,
    created_at: new Date(),
    updated_at: new Date(),
    action: 'delete',
    created_by: null,
    deleted_at: null,
    deleted_by: null,
    module: 'management',
    updated_by: null,
    type: 'Usuários',
  },
  {
    id: '60b7a679-609b-4964-a09e-b667114a8612',
    name: 'Permite visualizar os fornecedores',
    active: true,
    created_at: new Date(),
    updated_at: new Date(),
    action: 'get',
    created_by: 'bff37aa4-faaa-4e9a-9295-5c8ac7d107ef',
    deleted_at: null,
    deleted_by: null,
    module: 'registration',
    updated_by: null,
    type: 'Fornecedor',
  },
  {
    id: 'df838253-dcc7-471b-90a4-6709552ee204',
    name: 'Permite deletar os fornecedores',
    active: true,
    created_at: new Date(),
    updated_at: new Date(),
    action: 'delete',
    created_by: 'bff37aa4-faaa-4e9a-9295-5c8ac7d107ef',
    deleted_at: null,
    deleted_by: null,
    module: 'registration',
    updated_by: null,
    type: 'Fornecedor',
  },
  {
    id: '58acf1fb-3238-462f-83d6-0e6ade158dab',
    name: 'Permite deletar os produtos',
    active: true,
    created_at: new Date(),
    updated_at: new Date(),
    action: 'delete',
    created_by: 'bff37aa4-faaa-4e9a-9295-5c8ac7d107ef',
    deleted_at: null,
    deleted_by: null,
    module: 'registration',
    updated_by: null,
    type: 'Produto',
  },
  {
    id: '0246842f-ece2-4d5c-a87a-94ab0ecaa631',
    name: 'Permite criar/alterar os produtos',
    active: true,
    created_at: new Date(),
    updated_at: new Date(),
    action: 'post_put',
    created_by: 'bff37aa4-faaa-4e9a-9295-5c8ac7d107ef',
    deleted_at: null,
    deleted_by: null,
    module: 'registration',
    updated_by: null,
    type: 'Produto',
  },
  {
    id: '00baaad5-69a0-4183-9486-9c90c7087ebc',
    name: 'Permite visualizar os produtos',
    active: true,
    created_at: new Date(),
    updated_at: new Date(),
    action: 'get',
    created_by: 'bff37aa4-faaa-4e9a-9295-5c8ac7d107ef',
    deleted_at: null,
    deleted_by: null,
    module: 'registration',
    updated_by: null,
    type: 'Produto',
  },
  {
    id: 'b53dcff8-2c1b-44c0-bab7-e2cffd8cb743',
    name: 'Permite visualizar as categorias',
    active: true,
    created_at: new Date(),
    updated_at: new Date(),
    action: 'get',
    created_by: 'bff37aa4-faaa-4e9a-9295-5c8ac7d107ef',
    deleted_at: null,
    deleted_by: null,
    module: 'registration',
    updated_by: null,
    type: 'Categoria',
  },
  {
    id: 'd42fb70e-41bc-4e65-a140-75e0eb3f2033',
    name: 'Permite deletar categorias',
    active: true,
    created_at: new Date(),
    updated_at: new Date(),
    action: 'delete',
    created_by: 'bff37aa4-faaa-4e9a-9295-5c8ac7d107ef',
    deleted_at: null,
    deleted_by: null,
    module: 'registration',
    updated_by: null,
    type: 'Categoria',
  },
  {
    id: '0844aafd-cd0b-412b-b3d1-e7e673b486cc',
    name: 'Permite criar/alterar categorias',
    active: true,
    created_at: new Date(),
    updated_at: new Date(),
    action: 'post_put',
    created_by: 'bff37aa4-faaa-4e9a-9295-5c8ac7d107ef',
    deleted_at: null,
    deleted_by: null,
    module: 'registration',
    updated_by: null,
    type: 'Categoria',
  },
  {
    id: 'bbe5ba19-bead-4cf1-9a4b-00d1ba6eb91e',
    name: 'Permite criar/alterar pedido de compra',
    active: true,
    created_at: new Date(),
    updated_at: new Date(),
    action: 'post_put',
    created_by: 'bff37aa4-faaa-4e9a-9295-5c8ac7d107ef',
    deleted_at: null,
    deleted_by: null,
    module: 'financial',
    updated_by: null,
    type: 'Solicitação',
  },
  {
    id: '29050618-ad37-45b9-92f8-471a40805927',
    name: 'Permite visualizar pedidos de compra',
    active: true,
    created_at: new Date(),
    updated_at: new Date(),
    action: 'get',
    created_by: 'bff37aa4-faaa-4e9a-9295-5c8ac7d107ef',
    deleted_at: null,
    deleted_by: null,
    module: 'financial',
    updated_by: null,
    type: 'Solicitação',
  },
  {
    id: '5ae84d4c-7c2f-423b-a71c-6eec23d7ea71',
    name: 'Permite deletar pedido de compra',
    active: true,
    created_at: new Date(),
    updated_at: new Date(),
    action: 'delete',
    created_by: 'bff37aa4-faaa-4e9a-9295-5c8ac7d107ef',
    deleted_at: null,
    deleted_by: null,
    module: 'financial',
    updated_by: null,
    type: 'Solicitação',
  },
  {
    id: 'a673d743-121e-49df-bb46-0101ce83bc10',
    name: 'Permite criar/alterar orçamento',
    active: true,
    created_at: new Date(),
    updated_at: new Date(),
    action: 'post_put',
    created_by: 'bff37aa4-faaa-4e9a-9295-5c8ac7d107ef',
    deleted_at: null,
    deleted_by: null,
    module: 'financial',
    updated_by: null,
    type: 'Orçamento',
  },
  {
    id: '3ac0bee3-5c8c-4300-acdf-73c3159ece3e',
    name: 'Permite deletar orçamentos',
    active: true,
    created_at: new Date(),
    updated_at: new Date(),
    action: 'delete',
    created_by: 'bff37aa4-faaa-4e9a-9295-5c8ac7d107ef',
    deleted_at: null,
    deleted_by: null,
    module: 'financial',
    updated_by: null,
    type: 'Orçamento',
  },
  {
    id: '38aea582-7122-40b3-91be-aae31fdc7a47',
    name: 'Permite visualizar orçamentos',
    active: true,
    created_at: new Date(),
    updated_at: new Date(),
    action: 'get',
    created_by: 'bff37aa4-faaa-4e9a-9295-5c8ac7d107ef',
    deleted_at: null,
    deleted_by: null,
    module: 'financial',
    updated_by: null,
    type: 'Orçamento',
  },
  {
    id: 'fcf26c40-d33e-42e1-8b46-202d4371e7c8',
    name: 'Permite Aprovar/Rejeitar orçamento',
    active: true,
    created_at: new Date(),
    updated_at: new Date(),
    action: 'post_put',
    created_by: 'bff37aa4-faaa-4e9a-9295-5c8ac7d107ef',
    deleted_at: null,
    deleted_by: null,
    module: 'financial',
    updated_by: null,
    type: 'Aprovar/Reprovar Orçamento',
  },
  {
    id: '4a889619-8e9e-40e6-a3d8-8f92d7950ea9',
    name: 'Permite verificar todos os locais de trabalho',
    active: true,
    created_at: new Date(),
    updated_at: new Date(),
    action: 'get',
    created_by: '12a16c4b-b6fc-4dda-8d76-675950d90162',
    deleted_at: null,
    deleted_by: null,
    module: 'registration',
    updated_by: null,
    type: 'Local de Trabalho',
  },
  {
    id: '4c8fd3b2-721a-48bf-b4e5-28c8b552c705',
    name: 'Permite deletar um ou mais locais de trabalho',
    active: true,
    created_at: new Date(),
    updated_at: new Date(),
    action: 'delete',
    created_by: '12a16c4b-b6fc-4dda-8d76-675950d90162',
    deleted_at: null,
    deleted_by: null,
    module: 'registration',
    updated_by: null,
    type: 'Local de Trabalho',
  },
  {
    id: 'fb23b83f-7209-4ca1-9944-4b1b4459a63e',
    name: 'Permite criar/alterar um local de trabalho',
    active: true,
    created_at: new Date(),
    updated_at: new Date(),
    action: 'post_put',
    created_by: '12a16c4b-b6fc-4dda-8d76-675950d90162',
    deleted_at: null,
    deleted_by: null,
    module: 'registration',
    updated_by: null,
    type: 'Local de Trabalho',
  },
  {
    id: '8da43892-7c9f-4cb9-83fb-95661ce70347',
    name: 'Permite criar/alterar Unid. de medida',
    active: true,
    created_at: new Date(),
    updated_at: new Date(),
    action: 'post_put',
    created_by: '12a16c4b-b6fc-4dda-8d76-675950d90162',
    deleted_at: null,
    deleted_by: null,
    module: 'registration',
    updated_by: null,
    type: 'Unid. de Medida',
  },
  {
    id: 'b3311602-4380-4e21-93da-5170ebfb4de0',
    name: 'Permite deletar Unid. de medida',
    active: true,
    created_at: new Date(),
    updated_at: new Date(),
    action: 'delete',
    created_by: '12a16c4b-b6fc-4dda-8d76-675950d90162',
    deleted_at: null,
    deleted_by: null,
    module: 'registration',
    updated_by: null,
    type: 'Unid. de Medida',
  },
  {
    id: '68182078-38b1-4c57-bab4-98e0726c70f9',
    name: 'Permite ver as Unid. de medida',
    active: true,
    created_at: new Date(),
    updated_at: new Date(),
    action: 'get',
    created_by: '12a16c4b-b6fc-4dda-8d76-675950d90162',
    deleted_at: null,
    deleted_by: null,
    module: 'registration',
    updated_by: null,
    type: 'Unid. de Medida',
  },
];
